name: Build and Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Extract version
        id: package_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gemini-navigator-v${{ steps.package_version.outputs.VERSION }}
          path: dist/*.user.js

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.package_version.outputs.VERSION }}
          name: Gemini Navigator v${{ steps.package_version.outputs.VERSION }}
          draft: true
          files: dist/*.user.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
